services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django-web
    ports:
      - "8080:8000"
    working_dir: /work
    volumes:
      - ..:/work:cached
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
